### ISSUE TITLE
What is the version of rdkit?

### ISSUE THREAD

**Issue by kdpan** [drorlab/atom3d#32]
Traceback (most recent call last):
  File "data_TL.py", line 4, in <module>
    from rdkit import Chem
  File "/home/panfulu/anaconda3/envs/atom3d/lib/python3.6/site-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/home/panfulu/anaconda3/envs/atom3d/lib/python3.6/site-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/panfulu/anaconda3/envs/atom3d/lib/python3.6/site-packages/rdkit/DataStructs/../../../../libRDKitDataStructs.so.1)

When I use the rdkit 2020.09, it will meet a mistake. What is the version of rdkit?

**Comment by kdpan** [comment]
If import torch.utils.data first, it will mistake.
If import rdkit first, it will not mistake.

(atom3d) [panfulu@localhost cnn3d ]$python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch.utils.data import Dataset
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/panfulu/anaconda3/envs/atom3d/lib/python3.6/site-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/home/panfulu/anaconda3/envs/atom3d/lib/python3.6/site-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/panfulu/anaconda3/envs/atom3d/lib/python3.6/site-packages/rdkit/DataStructs/../../../../libRDKitDataStructs.so.1)
>>> exit()
(atom3d) [panfulu@localhost cnn3d ]$python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
>>> from torch.utils.data import Dataset
>>> exit()

**Comment by martinvoegele** [comment]
Hi, thanks for reporting this!

I use RDKit 2021.03.4 and PyTorch 1.9.0 with Python 3.6.13 and can import them either way.

**Comment by martinvoegele** [comment]
I'm closing this issue.
Feel free to reopen it if anything has remained unclear or raise a new issue if something else comes up.
